name: Release

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  version:
    uses: zareix/gh-actions/.github/workflows/get-version.yml@main

  docker:
    name: Docker
    needs: version
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: zareix/gh-actions/.github/workflows/docker.yml@main
    with:
      tag: ${{ needs.version.outputs.version }}
      registry: ghcr.io
      image-name: ${{ github.repository }}
      push-image: true
      platforms: linux/amd64 #,linux/arm64

  release:
    name: Create release
    needs:
      - version
      - docker
    uses: zareix/gh-actions/.github/workflows/release.yml@main
    with:
      tag: ${{ needs.version.outputs.version }}
